### ISSUE TITLE
Meliora Testlab Pipeline steps dropped from 2.481 builds

### ISSUE THREAD

**Issue by MarkEWaite** [jenkins-infra/pipeline-steps-doc-generator#498]
### Reproduction steps

1. The upgrade from Java EE 8 to Jakarta EE 9 has caused the Pipeline steps documentation generator to report a null pointer exception while trying to extract the [Pipeline steps](https://www.jenkins.io/doc/pipeline/steps/meliora-testlab/) for the plugin.

The ci.jenkins.io logfile reports:

```
21:19:04  [WARNING] Cannot instantiate fi.meliora.testlab.ext.jenkins.TestlabNotifier$DescriptorImpl 
21:19:04  java.lang.NullPointerException: Cannot invoke "jakarta.servlet.ServletContext.getAttribute(String)" because "c" is null
21:19:04  	at hudson.util.PluginServletFilter.getInstance(PluginServletFilter.java:87)
21:19:04  	at hudson.util.PluginServletFilter.addFilter(PluginServletFilter.java:115)
21:19:04  	at hudson.util.PluginServletFilter.addFilter(PluginServletFilter.java:134)
21:19:04  	at PluginClassLoader for meliora-testlab//fi.meliora.testlab.ext.jenkins.TestlabNotifier$DescriptorImpl.<init>(TestlabNotifier.java:682)
```

### Expected Results

Pipelines steps documentation for plugin should be generated

### Actual Results

Pipeline steps are not generated.

### Anything else?

I've submitted a pull request that may resolve the issue:

* https://github.com/jenkinsci/meliora-testlab-plugin/pull/17

**Comment by MarkEWaite** [comment]
Fixed by the 1.24 release of the Meliora test lab plugin.  Visible as [Pipeline steps reference](https://www.jenkins.io/doc/pipeline/steps/meliora-testlab/)
